### PR TITLE
Test Markdown conversion

### PR DESCRIPTION
**Pull request by rgovert**
renamed versions-release-notes in the sdk documentation to .md and then edited the file for markdown.

**Note:** I know I'm missing something. When the doc was renamed to a .md it no longer shows up in the document tree. Please let me know what I need to change. 

Also if you could review the markdown format. I basically copied what Ben did on the otter docs, but I want to make sure I'm not missing anything obvious

### CODE REVIEW

**Comment by apapadimoulis** [comment]
Does it look the same?

**Comment by rgovert** [comment]
I can't see it on localhost at all, it just disappeared from the doc menu tree (see attached picture) and if I try to type the url in, it just redirects to various docs home. I'm thinking it is still looking for an .htm file, not an .md file, and there's something I need to change. I don't know what that is though.

Is it more complicated than just renaming the .htm file to a .md file and converting the text to markdown  format inside the file?

Or.... could I need a new web server?

image

**Comment by rgovert** [comment]
@apapadimoulis so I converted all of the inedosdk docs to markdown and they still don't show up on localhost so I have no idea what I'm missing. I could see them in a markdown preview in Atom, and everything looked good in there, but there's no way to tell if our classes our working correctly.

I need to know what I'm missing, be it a back-end thing, a new web server, or something else... so that I'll be able to teach Nikki, Cheyenne, and Marisa later

**Comment by rgovert** [comment]
I finally got everything to work. I was also able to determine that when I push the commit to GitHub from within Atom, it automatically deploys my branch to test. Would this be a problem for any reason, should I not do it from within Atom anymore?

I found editing the docs in Atom instead of Visual studio to be easier which is why I've been using that instead. It has a nice integration with GitHub/GitHub desktop.

Otherwise. These should be good to go. Today i'll be working on a document so that Nikki, Cheyenne and Marisa can learn how to do markdown edits as well.

**Comment by jrasch** [comment]
Just FYI we have BuildMaster configured to auto-deploy to test on every push, and it's configured such that only users with "force" permissions can push non-master branches to production.

**Pull request merged**
